formatters:
    plain:
        format: '%(levelname)-8s %(asctime)s %(name)-45s %(funcName)-35s %(lineno)5d: %(message)s'

root:
    level: INFO
    handlers: ['console']

loggers:
    pika:
        level: INFO
    amqp_manager:
        level: INFO

handlers:
    console:
        class: logging.StreamHandler
        formatter: plain

version: 1
disable_existing_loggers: true
