formatters:
    color:
        '()': flow.util.log_formatter.ColorFormatter
        fmt: '%(levelname)-23s %(asctime)s %(name)-60s %(funcName)-50s %(lineno)5d: %(message)s'

root:
    level: INFO
    handlers: ['console']

loggers:
    pika:
        level: INFO
    amqp_manager:
        level: INFO

handlers:
    console:
        class: logging.StreamHandler
        formatter: color

version: 1
disable_existing_loggers: true
