formatters:
    color:
        '()': amqp_service.log_formatter.ColorFormatter
        fmt: '%(levelname)-23s %(asctime)s %(name)-60s %(funcName)-50s %(lineno)5d: %(message)s'
    plain:
        format: '%(levelname)-8s %(asctime)s %(name)-45s %(funcName)-35s %(lineno)5d: %(message)s'

root:
    level: INFO
    handlers: ['console', 'file']

loggers:
    pika:
        level: INFO
    amqp_manager:
        level: INFO

handlers:
    console:
        class: logging.StreamHandler
        formatter: color
    file:
        class: logging.FileHandler
        formatter: plain
        filename: example.log

version: 1
disable_existing_loggers: true
